const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g,c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
let state, view = 'radar', filter = 'All updates', query = '', collecting = false;
let accessToken = sessionStorage.getItem('radar-token') || '';
const names = {radar:'My radar',stack:'My tech stack',history:'Digest history',sources:'Sources',preferences:'Preferences'};
const tech = id => state.catalog.find(t => t.id === id);
const icon = id => `<span class="tech-icon ${esc(id)}">${esc(tech(id)?.icon || id)}</span>`;
const date = value => new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'});
const sampleMode = () => state.items.length === 0;
const items = () => (sampleMode() ? state.samples : state.items).filter(x => state.settings.technologies.includes(x.tech));
let toastTimer;
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').classList.remove('show'),6000); }
async function api(path, method = 'GET', data) {
  const response = await fetch(`/api/${path}`,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`,'X-Radar-CSRF':state?.csrf || ''},body:data === undefined ? undefined : JSON.stringify(data)});
  const result = await response.json(); if (!response.ok) { if(response.status === 401) login(); throw new Error(result.error || 'Request failed.'); } return result;
}
async function load() { state = await api('state'); render(); }
function heading(title, subtitle, buttons = '') { return `<div class="page-heading"><div><p class="eyebrow">YOUR ENGINEERING BRIEFING</p><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="actions">${buttons}</div></div>`; }
function render() {
  document.querySelectorAll('[data-view]').forEach(el => el.classList.toggle('active',el.dataset.view === view));
  $('#breadcrumb').innerHTML = `Workspace <span>/</span> ${names[view]}`;
  $('#nav-count').textContent = items().length;
  $('#app').innerHTML = ({radar:radar,stack:stack,history:history,sources:sources,preferences:preferences}[view])();
  bind();
}
function radar() {
  const all = items(), high = all.filter(x => x.impact === 'High').length, isSample = sampleMode();
  return heading('Your stack. In focus.', 'The updates that matter to your tests, tools, and pipelines.', `<button class="secondary" id="preview">▤ Preview digest</button><button class="primary" id="refresh" ${collecting?'disabled':''}>↻ ${collecting?'Collecting…':'Check for updates'}</button>`) +
  `<div class="briefing-banner"><div class="orbit">◎</div><div><h2>A little less noise. A lot more signal.</h2><p>${isSample?'Explore a sample briefing, then collect your first official updates.':`${all.length} updates from your stack, organized around what needs your attention.`}</p></div><span class="banner-tag">${isSample?'◌ Sample briefing':'◉ Official sources'}</span></div>
  <div class="stats"><div class="stat"><div class="stat-top">Technologies tracked <span>▦</span></div><strong>${state.settings.technologies.length}</strong><small>in your stack</small></div><div class="stat"><div class="stat-top">${isSample?'Sample updates':'Updates collected'} <span>◷</span></div><strong>${all.length}</strong><small>${isSample?'illustrative only':'in your radar'}</small></div><div class="stat"><div class="stat-top">Worth your attention <span>↗</span></div><strong>${high.toString().padStart(2,'0')}</strong><small>high impact</small></div><div class="stat"><div class="stat-top">Digest frequency <span>▤</span></div><strong>${{daily:'Daily',weekly:'Weekly',important:'Priority'}[state.settings.frequency]}</strong><small>${state.settings.enabled?'enabled':'not sending yet'}</small></div></div>
  <div class="content-grid"><section><div class="feed-head"><h2>Your update feed</h2><span>${isSample?'DEMO · NOT LIVE NEWS':state.collection?`CHECKED ${esc(date(state.collection.at))}`:'READY TO COLLECT'}</span></div><div class="filters">${['All updates','Must Know','Useful','Optional'].map((label,i) => `<button class="filter ${filter===label?'selected':''}" data-filter="${label}" aria-pressed="${filter===label}">${label}${i===0?` <b>${all.length}</b>`:''}</button>`).join('')}<input class="search" id="search" type="search" placeholder="Search updates…" aria-label="Search updates" value="${esc(query)}"></div><div id="feed">${feed()}</div></section>
  <aside class="right-column"><div class="side-panel"><div class="panel-head"><h3>Your tech stack</h3><button class="text-button" data-view="stack">Manage ↗</button></div><div class="stack-chips">${state.settings.technologies.slice(0,9).map(id => `<span class="chip">${esc(tech(id).name)}</span>`).join('')}${state.settings.technologies.length>9?`<span class="chip">+${state.settings.technologies.length-9} more</span>`:''}</div><p class="separator">Tailored to the tools you actually use.</p></div><div class="side-panel"><div class="delivery-icon">✉</div><h4>Your next good read.</h4><p>${state.settings.enabled?'Your digest is configured. Delivery runs when the scheduler and email provider are enabled.':'Choose when your radar lands in your inbox. Five to ten headlines. No endless scrolling.'}</p><button class="secondary" data-view="preferences">Set up your digest <span>→</span></button></div><div class="side-panel"><div class="panel-head"><h3>Signal, straight from the source</h3></div><p>Official release notes and announcements. Duplicate links and promotional headlines filtered out.</p><div class="source-status"><i></i>${state.integrations.ai?'AI ranking configured':'Transparent rule-based ranking'}</div></div><div class="note"><strong>A note on relevance</strong><br>Impact ratings are a starting point. Always check the original source against your own environment.</div></aside></div>`;
}
function card(x) { return `<article class="update-card"><div class="card-top">${icon(x.tech)}<strong>${esc(tech(x.tech)?.name)}</strong><span class="kind">${esc(x.kind)}</span><span class="card-date">${x.sample?'EXAMPLE':esc(date(x.published))}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><div class="card-bottom"><span class="impact ${x.impact.toLowerCase()}">${x.impact} impact</span><span class="action-needed">${x.action?'↗ Action needed':'No action needed'}</span><button class="explain" data-explain="${x.id}">✧ Explain this</button><a class="source-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${x.sample?'Source hub':'Source'} ↗</a></div></article>`; }
function feed() {
  const matching = items().filter(x => `${x.title} ${x.summary} ${tech(x.tech)?.name}`.toLowerCase().includes(query.toLowerCase()));
  const sections = [['High','Must Know'],['Medium','Useful'],['Low','Optional']];
  const html = sections.filter(([,name]) => filter === 'All updates' || filter === name).map(([impact,name]) => { const group = matching.filter(x => x.impact === impact).sort((a,b) => b.published.localeCompare(a.published)); return group.length ? `<div class="section-label ${impact.toLowerCase()}"><span class="section-dot"></span>${name}<span>· ${group.length}</span></div>${group.map(card).join('')}` : ''; }).join('');
  return html || '<div class="empty"><h3>Clear skies here.</h3><p>No updates match these filters. Try another search or add technologies to your stack.</p></div>';
}
function stack() { return heading('Make it your stack.', 'Select the tools you use. Add exact project versions for release comparison.') + `<form id="stack-form">${[...new Set(state.catalog.map(t => t.category))].map(category => `<h2 class="group-title">${category}</h2><div class="tech-grid">${state.catalog.filter(t => t.category===category).map(t => `<div class="tech-tile"><label>${icon(t.id)}${esc(t.name)}<input type="checkbox" name="technology" value="${t.id}" ${state.settings.technologies.includes(t.id)?'checked':''}></label><label class="version-label" for="version-${t.id}">Project version (optional)</label><input type="text" id="version-${t.id}" name="version-${t.id}" value="${esc(state.settings.versions[t.id] || '')}" placeholder="e.g. 1.50.0" maxlength="40"></div>`).join('')}</div>`).join('')}<button class="primary" type="submit">Save my stack</button></form>`; }
function preferences() { return heading('A digest on your terms.', 'Just your email address. No inbox access, ever.') + `<form class="form-panel" id="preferences-form"><label class="field">Email address<small>Your digest will only go to this address.</small><input type="email" name="email" placeholder="you@example.com" value="${esc(state.settings.email)}" maxlength="254"></label><label class="field">Delivery frequency<select name="frequency">${[['daily','Daily — a quick daily briefing'],['weekly','Weekly — the week in perspective'],['important','Important only — high-impact updates']].map(([v,t]) => `<option value="${v}" ${v===state.settings.frequency?'selected':''}>${t}</option>`).join('')}</select><small>Daily delivery: 8:00 a.m. Eastern Time (adjusts for daylight saving). Weekly intervals start after the first delivery. Important-only is checked hourly.</small></label><label class="field">Maximum headlines<select name="limit">${[5,6,7,8,9,10].map(n => `<option ${n===state.settings.limit?'selected':''}>${n}</option>`).join('')}</select><small>We send fewer when there is less to report, and never repeat a delivered update.</small></label><label class="checkbox-row"><input type="checkbox" name="enabled" ${state.settings.enabled?'checked':''}><span>Enable email digests for my selected technologies</span></label><button class="primary" type="submit">Save preferences</button><h2 class="group-title">Connections</h2><div class="integration-row">Email delivery · Resend<span>${state.integrations.email?'Configured':'Needs API key & sender'}</span></div><div class="integration-row">AI ranking · OpenAI<span>${state.integrations.ai?'Configured':'Optional · using rules'}</span></div><div class="integration-row">Automatic update schedule<span>${state.integrations.scheduler?'Enabled':'Disabled'}</span></div><p class="note">Connect services through the server’s .env file. API keys stay on the server. Enabling delivery here alone will not send email until the scheduler and Resend are configured.</p></form>`; }
function sources() { return heading('Go straight to the source.', 'Official feeds, transparent coverage, and visible collection health.') + `<p class="inline-notice">Coverage is intentionally specific: JavaScript uses V8, C# uses Roslyn, Docker uses Moby, Postman uses Newman, and AI testing uses Playwright MCP. These feeds are not exhaustive security monitoring.</p>${state.catalog.map(t => { const health = state.collection?.sources.find(s => s.tech===t.id); return `<div class="source-row"><div><strong>${esc(t.name)}</strong><small>${esc(new URL(t.source.home).host)} · ${t.source.type==='github'?'Official repository releases':'Official RSS / Atom'} · ${!state.settings.technologies.includes(t.id)?'Not tracked':health?health.ok?`Checked · ${health.count} new`:`Failed: ${esc(health.error)}`:'Not checked yet'}</small></div><a href="${esc(t.source.home)}" target="_blank" rel="noopener noreferrer">Visit source ↗</a></div>`; }).join('')}`; }
function history() { return heading('The signal stays with you.', 'A searchable archive of successfully sent digests.') + `<input class="search" id="history-search" aria-label="Search digest history" placeholder="Search history…"><div id="history-list">${historyList('')}</div>`; }
function historyList(term) { const entries = state.history.filter(h => JSON.stringify(h.items).toLowerCase().includes(term.toLowerCase())); return entries.length ? entries.map(h => `<details class="history-entry"><summary>${esc(date(h.at))} · ${h.items.length} updates · ${esc(h.status)}</summary>${h.items.map(card).join('')}</details>`).join('') : '<div class="empty"><h3>Your first briefing starts here.</h3><p>Sent digests will appear here. Configure your email and schedule in Preferences.</p><button class="secondary" data-view="preferences">Set up email delivery →</button></div>'; }
function showDialog(html) { $('#dialog-body').innerHTML = html; if (!$('#dialog').open) $('#dialog').showModal(); }
function explain(id) {
  const x = [...state.items,...state.samples,...state.history.flatMap(h=>h.items)].find(x => x.id===id); if (!x) return;
  showDialog(`<p class="eyebrow">${x.sample?'ILLUSTRATIVE EXAMPLE':esc(x.ranking)} · PRACTICAL SDET CONTEXT</p><h2>${esc(x.title)}</h2><p>${esc(x.summary)}</p><h3>What to check in your project</h3><p>${esc(x.versionNote || 'Add a project version in My tech stack to compare releases.')}</p><ul><li>Read the original announcement for affected versions and migration steps.</li><li>Try the update in an isolated branch with your pinned dependencies.</li><li>Run your smoke, API, and browser regression suites before promoting it.</li></ul><p>These are general review steps, not a verified compatibility assessment.</p><div class="actions"><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open original source ↗</a>${x.action?`<button class="secondary" id="jira-draft">Draft an upgrade task</button>`:''}</div>`);
  if ($('#jira-draft')) $('#jira-draft').onclick = () => showDialog(`<p class="eyebrow">JIRA-READY DRAFT · NOT SUBMITTED</p><h2>Review ${esc(tech(x.tech)?.name)} update</h2><pre>${esc(`Summary: Assess ${x.title}\n\nSource: ${x.url}\nReason: ${x.summary}\n\nAcceptance criteria:\n- Confirm whether our project version is affected.\n- Review migration notes and update pinned dependencies if needed.\n- Run smoke and regression suites in CI.\n- Record rollback steps and results.\n\n${x.sample?'This is a sample task based on an illustrative update.':''}`)}</pre><p>Copy this draft into your issue tracker after verifying the source. No Jira connection is required.</p>`);
}
function preview() { const list = [...items()].sort((a,b) => ({High:3,Medium:2,Low:1}[b.impact]-{High:3,Medium:2,Low:1}[a.impact])).filter(x => state.settings.frequency!=='important' || x.impact==='High').slice(0,state.settings.limit); showDialog(`<p class="eyebrow">EMAIL PREVIEW ${sampleMode()?'· SAMPLE DATA':''}</p><h2>Your SDET Tech Radar</h2><p>${list.length} useful updates. A little context for your next engineering decision.</p>${list.length?list.map(card).join(''):'<p>No updates to include yet.</p>'}<p>This is a preview. No email has been sent.</p>`); }
function login() { showDialog('<h2>Unlock your radar</h2><p>Use the private dashboard access key saved during setup.</p><form id="login-form"><label class="field">Access token<input name="token" type="password" required autocomplete="current-password"></label><button class="primary">Continue</button></form>'); $('#login-form').onsubmit = async e => { e.preventDefault(); accessToken = new FormData(e.target).get('token'); sessionStorage.setItem('radar-token',accessToken); try { await load(); $('#dialog').close(); } catch(error) { toast(error.message); } }; }
function bind() {
  if ($('#search')) $('#search').oninput = e => { query = e.target.value; $('#feed').innerHTML = feed(); };
  if ($('#history-search')) $('#history-search').oninput = e => $('#history-list').innerHTML = historyList(e.target.value);
  if ($('#refresh')) $('#refresh').onclick = async () => { collecting = true; render(); try { const result = await api('collect','POST',{}); toast(result.message || `Collected ${result.added} new updates. ${result.sources.filter(s=>!s.ok).length} sources need attention.`); await load(); } catch(e) { toast(e.message); } finally { collecting = false; render(); } };
  if ($('#preview')) $('#preview').onclick = preview;
  if ($('#stack-form')) $('#stack-form').onsubmit = async e => { e.preventDefault(); const form = new FormData(e.target), versions = {}; state.catalog.forEach(t => { const v = form.get(`version-${t.id}`).trim(); if (v) versions[t.id] = v; }); await save({...state.settings,technologies:form.getAll('technology'),versions}); };
  if ($('#preferences-form')) $('#preferences-form').onsubmit = async e => { e.preventDefault(); const f = new FormData(e.target); await save({...state.settings,email:f.get('email'),frequency:f.get('frequency'),limit:Number(f.get('limit')),enabled:f.has('enabled')}); };
}
async function save(settings) { try { await api('settings','PUT',settings); await load(); toast('Your preferences are saved.'); } catch(e) { toast(e.message); } }
document.addEventListener('click',e => { const nav=e.target.closest('[data-view]'); if(nav){view=nav.dataset.view;render();window.scrollTo(0,0);} const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();}const x=e.target.closest('[data-explain]');if(x)explain(x.dataset.explain); });
$('#dialog .close').onclick = () => $('#dialog').close();
load().catch(e => { if(!$('#dialog').open) $('#app').innerHTML = `<div class="empty"><h2>Could not reach your radar.</h2><p>${esc(e.message)}</p><button class="secondary" id="retry">Try again</button></div>`; if($('#retry')) $('#retry').onclick=()=>location.reload(); });
