import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import worker,{cloudDue,sendCloudDigest} from './cloud-worker.js';
import { cloudStore } from './cloud-store.js';
import { defaults } from './catalog.js';
import { classify,hash } from './domain.js';
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync('cloud-schema.sql','utf8'));return {db,prepare(sql){const statement=db.prepare(sql);const bind=(...args)=>({first:async()=>statement.get(...args),all:async()=>({results:statement.all(...args)}),run:async()=>({meta:{changes:Number(statement.run(...args).changes)}})});return {...bind(),bind};}};}
const env={APP_TOKEN:'a-private-token-with-at-least-24-characters',DIGEST_EMAIL:'test@example.com',ENABLE_SCHEDULER:'true',EMAIL_FROM:'onboarding@resend.dev',RESEND_API_KEY:'fake',DELIVERY_TIME:'08:00',DELIVERY_TIMEZONE:'America/New_York'};
test('cloud API fails closed and protects preferences from cross-origin requests',async()=>{const db=database();try{assert.equal((await worker.fetch(new Request('https://radar.example/api/state'),{...env,DB:db})).status,401);assert.equal((await worker.fetch(new Request('https://radar.example/api/state',{headers:{Authorization:`Bearer ${env.APP_TOKEN}`}}),{...env,APP_TOKEN:'',DB:db})).status,401);const res=await worker.fetch(new Request('https://radar.example/api/state',{headers:{Authorization:`Bearer ${env.APP_TOKEN}`}}),{...env,DB:db});assert.equal(res.status,200);const data=await res.json();assert.equal(data.settings.email,'test@example.com');const cross=await worker.fetch(new Request('https://radar.example/api/settings',{method:'PUT',headers:{Authorization:`Bearer ${env.APP_TOKEN}`,'X-Radar-CSRF':data.csrf,Origin:'https://attacker.example','Content-Type':'application/json'},body:JSON.stringify(defaults)}),{...env,DB:db});assert.equal(cross.status,403);}finally{db.db.close();}});
test('cloud database lock rejects a concurrent sender and protects a newer lease',async()=>{const db=database(),store=cloudStore(db);try{assert.equal(await store.lock('delivery','first',1000),true);assert.equal(await store.lock('delivery','second',1001),false);assert.equal(await store.lock('delivery','second',400000),true);await store.unlock('delivery','first');assert.equal(await store.lock('delivery','third',400001),false);}finally{db.db.close();}});
test('cloud sender retries the same payload and sends only once each Eastern day',async()=>{const db=database(),store=cloudStore(db),now=Date.parse('2026-09-20T12:00:00Z');let first;try{await store.add(classify({id:'cloud-one',tech:'node',title:'Node security release',body:'Security patch',url:'https://nodejs.org/',published:new Date(now).toISOString()}));await assert.rejects(sendCloudDigest(store,env,now,async(_url,options)=>{first=options;throw new Error('timeout');}));assert.equal((await store.history())[0].status,'pending');const result=await sendCloudDigest(store,env,now+60000,async(_url,options)=>{assert.deepEqual(options,first);return{json:async()=>({id:'test-email'})};});assert.equal(result.status,'sent');assert.equal((await sendCloudDigest(store,env,now+120000)).status,'not-due');}finally{db.db.close();}});
test('cloud schedule is disabled until explicitly activated',()=>{const settings={...defaults,email:'test@example.com',enabled:true,frequency:'daily'};assert.equal(cloudDue(settings,null,Date.parse('2026-09-20T12:00:00Z'),{...env,ENABLE_SCHEDULER:'false'}),false);assert.equal(cloudDue(settings,null,Date.parse('2026-09-20T12:00:00Z'),env),true);});
