CREATE TABLE IF NOT EXISTS kv (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS updates (id TEXT PRIMARY KEY, tech TEXT NOT NULL, published TEXT NOT NULL, payload TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS updates_published ON updates(published);
CREATE TABLE IF NOT EXISTS deliveries (id TEXT PRIMARY KEY, at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sources (tech TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS locks (name TEXT PRIMARY KEY, expires INTEGER NOT NULL, owner TEXT NOT NULL);
