import test from 'node:test';
import assert from 'node:assert/strict';
import { classify, chooseDigest, due, validateSettings, emailBody, versionNote } from './domain.js';
import { defaults } from './catalog.js';
import { openStore } from './store.js';
import { parseFeed, deliver } from './pipeline.js';
const item = {id:'one', tech:'node',title:'Node.js security release',body:'Fixes a security vulnerability',url:'https://nodejs.org/',published:new Date().toISOString(),version:'24.1.0'};
test('security and breaking changes take priority over routine releases',() => { assert.equal(classify(item).impact,'High');assert.equal(classify({...item,body:'Deprecated API',title:'Migration'}).kind,'Breaking change');assert.equal(classify({...item,body:'Test debugging fix',title:'Update'}).impact,'Medium'); });
test('digest excludes samples, untracked tools, delivered items and low priority when important-only',() => { const rows=[classify(item),{...classify(item),id:'two',sample:true},{...classify(item),id:'three',tech:'python'},{...classify(item),id:'four',impact:'Low'}]; const settings={...defaults,testingOnly:false,technologies:['node'],frequency:'important'}; assert.deepEqual(chooseDigest(rows,settings).map(x=>x.id),['one']); assert.equal(chooseDigest(rows,settings,new Set(['one'])).length,0); });
test('weekly and important schedules respect intervals and disabled delivery',() => { const now=Date.now();const settings={...defaults,testingOnly:false,technologies:['node'],frequency:'weekly',enabled:true,email:'a@example.com'};assert.equal(due(settings,new Date(now-86400000).toISOString(),now),false);assert.equal(due(settings,new Date(now-8*86400000).toISOString(),now),true);assert.equal(due({...settings,enabled:false},null,now),false);assert.equal(due({...settings,frequency:'important'},new Date(now-1800000).toISOString(),now),false); });
test('preferences reject invalid email, unknown technologies and invalid versions',() => { assert.throws(()=>validateSettings({...defaults,email:'bad'}));assert.throws(()=>validateSettings({...defaults,technologies:['unknown']}));assert.throws(()=>validateSettings({...defaults,enabled:true}));assert.throws(()=>validateSettings({...defaults,versions:{node:'<script>'}}));assert.equal(validateSettings({...defaults,email:'a@example.com'}).email,'a@example.com'); });
test('version comparisons distinguish newer and older releases without claiming exposure',() => { assert.match(versionNote(item,{versions:{node:'24.0.0'}}),/newer release/);assert.match(versionNote(item,{versions:{node:'24.2.0'}}),/at or above/);assert.match(versionNote({...item,version:'release-x'},{versions:{node:'24.0.0'}}),/unavailable/); });
test('official RSS and Atom normalize links and reject non-feed responses',() => { assert.equal(parseFeed('<rss><channel><item><title>A release</title><link>https://example.com/a</link><pubDate>Sat, 19 Sep 2026 00:00:00 GMT</pubDate></item></channel></rss>',{id:'node'})[0].url,'https://example.com/a');assert.equal(parseFeed('<feed><entry><title>A release</title><link href="https://example.com/a" rel="alternate"/><updated>2026-09-19</updated></entry></feed>',{id:'node'})[0].url,'https://example.com/a');assert.throws(()=>parseFeed('<html>Error</html>',{id:'node'})); });
test('HTML email escapes remote titles and rejects javascript URLs',() => { const html=emailBody([{...classify(item),title:'<img src=x onerror=alert(1)>',url:'javascript:alert(1)'}]);assert.ok(!html.includes('<img'));assert.ok(!html.includes('javascript:'));assert.ok(html.includes('&lt;img')); });
test('SQLite deduplicates updates and stores preferences',() => {const store=openStore(':memory:');assert.equal(store.add(classify(item)),1);assert.equal(store.add(classify(item)),0);store.set('settings',{...defaults,email:'persist@example.com'});assert.equal(store.settings().email,'persist@example.com');assert.equal(store.items().length,1);store.db.close();});
test('email failure is not recorded as sent and retry uses the identical idempotency key',async () => {
 const store=openStore(':memory:');store.set('settings',{...defaults,testingOnly:false,technologies:['node'],frequency:'weekly',enabled:true,email:'a@example.com'});store.add(classify(item));const saved={key:process.env.RESEND_API_KEY,from:process.env.EMAIL_FROM};process.env.RESEND_API_KEY='test';process.env.EMAIL_FROM='test@example.com';let first;
 try { await assert.rejects(deliver(store,async(_url,options)=>{first=options;throw new Error('network');}));assert.equal(store.get('lastSent',null),null);assert.equal(store.history()[0].status,'pending');const result=await deliver(store,async(_url,options)=>{assert.equal(options.headers['Idempotency-Key'],first.headers['Idempotency-Key']);assert.equal(options.body,first.body);return{json:async()=>({id:'email-test'})};});assert.equal(result.status,'sent');assert.equal(store.history()[0].status,'sent');assert.equal((await deliver(store)).status,'not-due'); }
 finally{if(saved.key===undefined)delete process.env.RESEND_API_KEY;else process.env.RESEND_API_KEY=saved.key;if(saved.from===undefined)delete process.env.EMAIL_FROM;else process.env.EMAIL_FROM=saved.from;store.db.close();}
});
